name: Task
description: Small, focused unit of work
title: "[Task] "
labels: ["task"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What outcome do we want?
    validations:
      required: true
  - type: textarea
    id: plan
    attributes:
      label: Plan
      description: What files will be touched? Any risks?
    validations:
      required: true
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
      description: Compile target, tests, docs updates
    validations:
      required: true
