name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle  # speed up Gradle builds

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --licenses <<< "y"
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble Debug (APK)
        run: ./gradlew :app:assembleDebug --stacktrace

      - name: Run detekt (non-blocking)
        run: ./gradlew detekt --stacktrace
        continue-on-error: true

      - name: Run ktlint (non-blocking)
        run: ./gradlew ktlintCheck --stacktrace
        continue-on-error: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
