name: No-Conflicts Guard
on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]
jobs:
  guard:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - name: Conflict marker check
        run: bash tools/no-conflicts.sh
